# --- Cluster identity and endpoints -------------------------------------

variable "cluster_name" {
  type        = string
  description = "Cluster name; names the generated core platform manifest."
}

variable "api_vip" {
  type        = string
  description = "Address of the RKE2 API endpoint (network.apiVIP in cluster.yaml)."
}

variable "api_host" {
  type        = string
  description = "DNS name of the RKE2 API endpoint; added to the API server certificate SANs."
}

variable "api_vip_mode" {
  type        = string
  default     = "external"
  description = "Elemental network.apiVIPMode: external skips MetalLB and expects a cloud load balancer."

  validation {
    condition     = contains(["managed", "external"], var.api_vip_mode)
    error_message = "api_vip_mode must be one of: managed, external."
  }
}

variable "tls_san" {
  type        = list(string)
  default     = []
  description = "Extra RKE2 tls-san entries written to server.yaml."
}

variable "vpc_cidr" {
  type        = string
  description = "Cluster network CIDR; used for the write-node-ip lookup and Traefik proxy-protocol trust."
}

variable "canal_iface_regex" {
  type        = string
  default     = null
  description = "Flannel --iface-regex written to the canal HelmChartConfig; null keeps the chart default."
}

variable "pod_veth_mtu" {
  type        = number
  default     = null
  description = "Calico vethuMTU written to the canal HelmChartConfig; null keeps the chart default."
}

variable "ingress_controller" {
  type        = string
  default     = "traefik"
  description = "RKE2 ingress-controller setting. Only traefik adds a HelmChartConfig."

  validation {
    condition     = contains(["none", "traefik", "ingress-nginx"], var.ingress_controller)
    error_message = "ingress_controller must be one of: none, traefik, ingress-nginx."
  }
}

variable "rke2_token" {
  type        = string
  sensitive   = true
  description = "Shared RKE2 join token, generated by the provider module."
}

# --- Nodes ---------------------------------------------------------------

variable "nodes" {
  type = list(object({
    hostname = string
    type     = string
    init     = optional(bool, false)
    node_ip  = optional(string)
    role     = optional(string)
    pool     = optional(string)
  }))
  description = "Cluster nodes. type is server or agent; role is control_plane, worker or gpu (null: control_plane for servers, gpu for agents); pool is the node pool, matched by suse_storage_nodes; init marks the node that bootstraps the cluster; node_ip pins the RKE2 node-ip."

  validation {
    condition     = alltrue([for n in var.nodes : contains(["server", "agent"], n.type)])
    error_message = "nodes[*].type must be server or agent."
  }

  validation {
    condition     = alltrue([for n in var.nodes : n.role == null || contains(n.type == "server" ? ["control_plane"] : ["worker", "gpu"], coalesce(n.role, "-"))])
    error_message = "nodes[*].role must be control_plane for servers and worker or gpu for agents."
  }

  validation {
    condition     = length([for n in var.nodes : n if n.init]) <= 1
    error_message = "At most one node may have init = true."
  }

  validation {
    condition     = length(distinct([for n in var.nodes : n.hostname])) == length(var.nodes)
    error_message = "nodes[*].hostname must be unique."
  }
}

variable "user_data_max_bytes" {
  type        = number
  description = "Per-node user_data size limit of the platform; the plan fails when a node's Ignition exceeds it."
}

variable "compress_node_files" {
  type        = bool
  default     = false
  description = "Gzip the files embedded in per-node Ignition to save user_data space."
}

# --- Image content -------------------------------------------------------

variable "kernel_cmdline" {
  type        = string
  description = "Kernel command line of the built image, including ignition.platform.id and consoles."
}

variable "elemental_image" {
  type        = string
  default     = "registry.suse.com/beta/uc/elemental:3.1.0-6.5"
  description = "Container image that runs `elemental customize` on the build host."
}

variable "image_disk_size" {
  type        = string
  default     = "8G"
  description = "Size of the raw image elemental builds (install.yaml raw.diskSize)."

  validation {
    condition     = can(regex("^[1-9][0-9]*[KMGT]$", var.image_disk_size))
    error_message = "image_disk_size must match <positive integer><K|M|G|T>, e.g. \"35G\"."
  }
}

variable "fips" {
  type        = bool
  default     = false
  description = "Set cryptoPolicy: fips in install.yaml. Every node must be FIPS-ready."
}

variable "components" {
  type        = list(string)
  default     = ["rancher", "gpu-operator", "local-path-provisioner", "aif-operator"]
  description = "AI Factory Helm charts to enable. Rendered in canonical order, not the order given."

  validation {
    condition = alltrue([
      for c in var.components : contains(
        ["cert-manager", "rancher", "gpu-operator", "local-path-provisioner", "suse-storage", "aif-operator"], c
      )
    ])
    error_message = "components entries must be one of: cert-manager, rancher, gpu-operator, local-path-provisioner, suse-storage, aif-operator."
  }

  validation {
    condition     = length(var.components) == length(distinct(var.components))
    error_message = "components must not contain duplicate entries."
  }

  validation {
    condition     = !(contains(var.components, "local-path-provisioner") && contains(var.components, "suse-storage"))
    error_message = "components cannot list both local-path-provisioner and suse-storage: both set the default StorageClass."
  }

  validation {
    condition     = !contains(var.components, "aif-operator") || contains(var.components, "rancher")
    error_message = "components lists aif-operator without rancher, which the AIF release manifest declares as its dependency."
  }
}

variable "suse_storage_nodes" {
  type        = list(string)
  default     = ["control_plane"]
  description = "Node roles (control_plane, worker, gpu) or pool names whose nodes get the Longhorn default-disk label when suse-storage is enabled. A node matches by role or by pool."

  validation {
    condition     = length(var.suse_storage_nodes) > 0 && alltrue([for r in var.suse_storage_nodes : contains(concat(["control_plane", "worker", "gpu"], [for n in var.nodes : n.pool if n.pool != null]), r)])
    error_message = "suse_storage_nodes must be a non-empty list of roles (control_plane, worker, gpu) or pool names."
  }

  validation {
    condition = !contains(var.components, "suse-storage") || length([
      for n in var.nodes : n if contains(var.suse_storage_nodes, coalesce(n.role, n.type == "server" ? "control_plane" : "gpu")) || contains(var.suse_storage_nodes, coalesce(n.pool, "-"))
    ]) >= 3
    error_message = "suse-storage needs at least three nodes holding its disks (suse_storage_nodes = ${jsonencode(var.suse_storage_nodes)})."
  }
}

variable "extra_butane_units" {
  type = list(object({
    name     = string
    enabled  = optional(bool, true)
    contents = optional(string)
  }))
  default     = []
  description = "Additional systemd units baked into the image through butane.yaml."
}

variable "extra_butane_files" {
  type = list(object({
    path     = string
    mode     = optional(number, 493)
    contents = string
  }))
  default     = []
  description = "Additional files baked into the image through butane.yaml. Mode is decimal."
}

variable "extra_config_files" {
  type        = map(string)
  default     = {}
  description = "Additional files for the elemental config dir, keyed by relative path (for example network/configure-network.sh)."
}

variable "enable_write_node_ip" {
  type        = bool
  default     = false
  description = "Add write-node-ip.sh and its unit to the image: on multi-NIC nodes it pins the RKE2 node-ip to the address inside vpc_cidr."
}

variable "extra_build_inputs" {
  type        = map(string)
  default     = {}
  description = "Extra values hashed into build_hash, for build inputs the provider module owns (for example the factory script)."
}

# --- Release manifest and beta overrides ---------------------------------

variable "aif_release" {
  type        = string
  default     = "2.3.0"
  description = "AI Factory release: a manifest URL (http:// or https://), or a version X.Y.Z[-pre] resolved to the SUSE/aif tag aif-operator-<version>."

  validation {
    condition     = can(regex("^https?://", var.aif_release)) || can(regex("^[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.]+)?$", var.aif_release))
    error_message = "aif_release must be a manifest URL (http:// or https://) or a full X.Y.Z version with an optional pre-release suffix, for example \"2.3.0\" or \"2.3.0-dev.2\"."
  }

  validation {
    condition = can(regex("^https?://", var.aif_release)) || !can(regex("^[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.]+)?$", var.aif_release)) || (
      tonumber(split(".", split("-", var.aif_release)[0])[0]) > 2 ||
      tonumber(split(".", split("-", var.aif_release)[0])[1]) >= 1
    )
    error_message = "aif_release versions must be 2.1.0 or newer: earlier tags have no uc-release-manifest/release_manifest.yaml."
  }
}

variable "core_platform_override" {
  type = object({
    os_image_base      = string
    os_image_iso       = string
    kubernetes_version = string
    kubernetes_image   = string
  })
  default     = null
  description = "Beta workaround: flatten the release manifest into a core platform manifest pinning these images. See docs/workarounds.md."

  validation {
    condition = var.core_platform_override == null || !can(regex(
      "registry\\.suse\\.com/elemental/base-os-kernel-default", var.core_platform_override.os_image_iso
    ))
    error_message = "core_platform_override.os_image_iso points at the GA elemental/ repo, whose elemental3ctl ignores initrdExtensions. Use a beta/uc/ image."
  }
}

variable "sysext_image_overrides" {
  type        = map(string)
  default     = {}
  description = "Beta workaround: per-extension OCI image overrides written into the release manifest, keyed by extension name."

  validation {
    condition     = alltrue([for name in keys(var.sysext_image_overrides) : can(regex("^[a-z0-9][a-z0-9._-]*$", name))])
    error_message = "sysext_image_overrides keys must be extension names as the release manifest spells them, for example \"suse-storage\"."
  }

  validation {
    condition     = alltrue([for image in values(var.sysext_image_overrides) : length(image) > 0 && !can(regex("[[:space:]'\"]", image))])
    error_message = "sysext_image_overrides values must be non-empty OCI image references without whitespace or quotes."
  }
}

# --- Accounts ------------------------------------------------------------

variable "root_password_hash" {
  type        = string
  sensitive   = true
  description = "Crypt hash for the root account (for example from `openssl passwd -6`)."
}

variable "node_username" {
  type        = string
  default     = "suse"
  description = "Unprivileged login account created on every node."
}

variable "node_user_password_hash" {
  type        = string
  sensitive   = true
  description = "Crypt hash for node_username."
}

variable "ssh_authorized_keys" {
  type        = list(string)
  description = "SSH public keys for node_username, and for root when permit_root_ssh is set."
}

variable "permit_root_ssh" {
  type        = bool
  default     = false
  description = "Allow SSH logins as root and install ssh_authorized_keys for it. Debug toggle."
}

# --- Registry and product credentials -------------------------------------

variable "appco_username" {
  type        = string
  default     = null
  sensitive   = true
  description = "Application Collection username. Required with local-path-provisioner or suse-storage; recommended with aif-operator so it can pull its workloads right after deployment."

  validation {
    condition = (
      !(contains(var.components, "local-path-provisioner") || contains(var.components, "suse-storage"))
      || try(trimspace(var.appco_username) != "" && trimspace(var.appco_password) != "", false)
    )
    error_message = "local-path-provisioner and suse-storage are pulled from Application Collection and need appco_username and appco_password."
  }

  validation {
    condition     = try(trimspace(var.appco_username) != "", false) == try(trimspace(var.appco_password) != "", false)
    error_message = "appco_username and appco_password must be set together."
  }
}

variable "appco_password" {
  type        = string
  default     = null
  sensitive   = true
  description = "Application Collection password or token, paired with appco_username."
}

variable "appco_registry" {
  type        = string
  default     = "dp.apps.rancher.io"
  description = "Registry host used by the Application Collection image pull secret."
}

variable "suse_registry_username" {
  type        = string
  default     = null
  sensitive   = true
  description = "SUSE registry username. Optional, set together with suse_registry_password; recommended with aif-operator."

  validation {
    condition     = try(trimspace(var.suse_registry_username) != "", false) == try(trimspace(var.suse_registry_password) != "", false)
    error_message = "suse_registry_username and suse_registry_password must be set together."
  }
}

variable "suse_registry_password" {
  type        = string
  default     = null
  sensitive   = true
  description = "SUSE registry password, paired with suse_registry_username."
}

variable "nvidia_api_key" {
  type        = string
  default     = null
  sensitive   = true
  description = "NVIDIA NGC API key. Optional, recommended with aif-operator; unset omits the nvidia credentials block."
}

variable "nvidia_username" {
  type        = string
  default     = "$oauthtoken"
  description = "NGC username paired with nvidia_api_key; NGC uses the literal $oauthtoken for API-key auth."

  validation {
    condition     = trimspace(var.nvidia_username) != ""
    error_message = "nvidia_username must not be empty."
  }
}

variable "gpu_driver_repository" {
  type        = string
  default     = "registry.opensuse.org/home/eminguez/branches/home/avicenzi/nvidia-for-bci-161/containerfile/third-party/nvidia"
  description = "Registry path of the precompiled NVIDIA driver container. Experimental default; see docs/workarounds.md."
  nullable    = false
}

variable "gpu_driver_version" {
  type        = string
  default     = "615"
  description = "NVIDIA driver branch of the precompiled driver container; must exist under gpu_driver_repository."
  nullable    = false
}

variable "rancher_hostname" {
  type        = string
  description = "Hostname of the Rancher ingress."
}

variable "rancher_bootstrap_password" {
  type        = string
  default     = null
  sensitive   = true
  description = "Rancher initial admin password; a random one is generated when null."
}

variable "image_rebuild" {
  type        = number
  default     = 0
  description = "Rebuild counter mixed into build_hash when greater than 0; bumping it forces a new image."
  nullable    = false
}
